version: "2"

services:
  reverse-proxy-container:
    image: "nginx_container:latest"
    container_name: nginx_container
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Seoul
    links:
      - hackathon
    depends_on:
      - hackathon
  express:
    build:
      context: ./app
    container_name: express_server
    ports:
      - 3000:3000
    networks:
      - default
